export const Errors =
{
    ACCOUNT_NOT_CREATED: "auth.authorizationSignUpRequired",
    PASSWORD_REQUIRED: "SESSION_PASSWORD_NEEDED",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    INVALID_PASSWORD: "INVALID_PASSWORD",
    INVALID_OTP: "PHONE_CODE_INVALID"

};

export const Status = 
{
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
};
